package cn.galudisu.fp.dao

import cn.galudisu.fp.models._

import scala.concurrent.Future

/**
 * Dao for action table
 */
trait ActionDao {
  /**
   * Find the action by ID
   * @param id the action ID
   * @return the ActionRow
   */
  def findById(id: Long): Future[Option[Tables.ActionRow]]

  /**
   * save a new action
   * @param name the action name
   * @return The action ID generated by MySQL
   */
  def save(name: String): Future[Long]
}